plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.0'
    id 'maven-publish'
}


repositories {
    mavenCentral()
    maven { url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/" }
    maven { url = "https://mvn.lumine.io/repository/maven-public/"}
    maven { url "https://repo.dmulloy2.net/repository/public/" }
    maven { url "https://repo.glaremasters.me/repository/concuncan/" }


    maven {
        url = 'https://repo.gin1.cc/repository/releases/'
        credentials {
            username = System.getenv("HolyRepoUser") ?: HolyRepoUser
            password = System.getenv("HolyRepoPassword") ?: HolyRepoPassword
        }
    }
}

dependencies {
    implementation project(':legacy')
    implementation 'com.github.luben:zstd-jni:1.5.5-11'
    compileOnly 'com.grinderwolf:slimeworldmanager-api:2.2.1'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    compileOnly "eu.koboo:en2do:$en2doVersion"
    compileOnly "org.spigotmc:spigot-api:1.21.9-R0.1-SNAPSHOT"
    compileOnly("org.spigotmc:spigot-1.8.8:dev:dev@jar")

    compileOnly 'net.dmulloy2:ProtocolLib:5.4.0'

    compileOnly("de.teamholy:holy-core-api:$coreVersion");
    compileOnly "de.teamholy:bukkit-core-api:$coreVersion"
}

allprojects {
    group = 'de.teamholy.replay'
    version = '1.0-SNAPSHOT'

    apply plugin: 'java'
    apply plugin: 'maven-publish'

    java {
        sourceCompatibility = 17
        targetCompatibility = 17
    }

    compileJava {
        options.encoding("UTF-8")
    }

    publishing {
        publications {
            maven(MavenPublication) {
                groupId project.group
                artifactId project.name
                version project.version
                from components.java
            }
        }
    }
}

shadowJar {
    archiveFileName = "holy-replay-${version}.jar"

    relocate 'com.comphenix.packetwrapper', 'de.teamholy.replay.libs.com.comphenix.packetwrapper'
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

build {
    dependsOn shadowJar
}